<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\District;
use App\Models\State;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            [ "state_name" => "Andaman and Nicobar Islands", "name" => "Nicobar" ],
            [ "state_name" => "Andaman and Nicobar Islands", "name" => "North and Middle Andaman" ],
            [ "state_name" => "Andaman and Nicobar Islands", "name" => "South Andaman" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Alluri Seetharama Raju" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Anakapalli" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Anantapur" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Annamaiah" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Bapatla" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Chittoor" ],
            [ "state_name" => "Andhra Pradesh", "name" => "East Godavari" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Eluru" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Guntur" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Kakinada" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Konaseema" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Krishna" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Kurnool" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Nandyala" ],
            [ "state_name" => "Andhra Pradesh", "name" => "NTR" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Palnadu" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Parvathipuram Manyam" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Prakasam" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Srikakulam" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Sri Potti Sriramulu Nellore" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Sri Sathya Sai" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Tirupati" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Visakhapatnam" ],
            [ "state_name" => "Andhra Pradesh", "name" => "Vizianagaram" ],
            [ "state_name" => "Andhra Pradesh", "name" => "West Godavari" ],
            [ "state_name" => "Andhra Pradesh", "name" => "YSR(Kadapa)" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Anjaw" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Capital Itanagar" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Changlang" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Dibang Valley" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "East Kameng" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "East Siang" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Kamle" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Kra Dadi" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Kurung Kumey" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Leparada" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Lohit" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Longding" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Lower Dibang Valley" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Lower Siang" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Lower Subansiri" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Namsai" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Pakke Kessang" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Papumpare" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Shi Yomi" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Siang" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Tawang" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Tirap" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Upper Siang" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "Upper Subansiri" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "West Kameng" ],
            [ "state_name" => "Arunachal Pradesh", "name" => "West Siang" ],
            [ "state_name" => "Assam", "name" => "Bajali" ],
            [ "state_name" => "Assam", "name" => "Baksa" ],
            [ "state_name" => "Assam", "name" => "Barpeta" ],
            [ "state_name" => "Assam", "name" => "Biswanath" ],
            [ "state_name" => "Assam", "name" => "Bongaigaon" ],
            [ "state_name" => "Assam", "name" => "Cachar" ],
            [ "state_name" => "Assam", "name" => "Charaideo" ],
            [ "state_name" => "Assam", "name" => "Chirang" ],
            [ "state_name" => "Assam", "name" => "Darrang" ],
            [ "state_name" => "Assam", "name" => "Dhemaji" ],
            [ "state_name" => "Assam", "name" => "Dhubri" ],
            [ "state_name" => "Assam", "name" => "Dibrugarh" ],
            [ "state_name" => "Assam", "name" => "Dima Hasao" ],
            [ "state_name" => "Assam", "name" => "Goalpara" ],
            [ "state_name" => "Assam", "name" => "Golaghat" ],
            [ "state_name" => "Assam", "name" => "Hailakandi" ],
            [ "state_name" => "Assam", "name" => "Hojai" ],
            [ "state_name" => "Assam", "name" => "Jorhat" ],
            [ "state_name" => "Assam", "name" => "Kamrup" ],
            [ "state_name" => "Assam", "name" => "Kamrup Metropolitan" ],
            [ "state_name" => "Assam", "name" => "Karbi Anglong" ],
            [ "state_name" => "Assam", "name" => "Karimganj" ],
            [ "state_name" => "Assam", "name" => "Kokrajhar" ],
            [ "state_name" => "Assam", "name" => "Lakhimpur" ],
            [ "state_name" => "Assam", "name" => "Majuli" ],
            [ "state_name" => "Assam", "name" => "Morigaon" ],
            [ "state_name" => "Assam", "name" => "Nagaon" ],
            [ "state_name" => "Assam", "name" => "Nalbari" ],
            [ "state_name" => "Assam", "name" => "Sibsagar" ],
            [ "state_name" => "Assam", "name" => "Sonitpur" ],
            [ "state_name" => "Assam", "name" => "South Salmara-Mankachar" ],
            [ "state_name" => "Assam", "name" => "Tamulpur" ],
            [ "state_name" => "Assam", "name" => "Tinsukia" ],
            [ "state_name" => "Assam", "name" => "Udalguri" ],
            [ "state_name" => "Assam", "name" => "West Karbi Anglong" ],
            [ "state_name" => "Bihar", "name" => "Araria" ],
            [ "state_name" => "Bihar", "name" => "Arwal" ],
            [ "state_name" => "Bihar", "name" => "Aurangabad" ],
            [ "state_name" => "Bihar", "name" => "Banka" ],
            [ "state_name" => "Bihar", "name" => "Begusarai" ],
            [ "state_name" => "Bihar", "name" => "Bhagalpur" ],
            [ "state_name" => "Bihar", "name" => "Bhojpur" ],
            [ "state_name" => "Bihar", "name" => "Buxar" ],
            [ "state_name" => "Bihar", "name" => "Darbhanga" ],
            [ "state_name" => "Bihar", "name" => "Gaya" ],
            [ "state_name" => "Bihar", "name" => "Gopalganj" ],
            [ "state_name" => "Bihar", "name" => "Jamui" ],
            [ "state_name" => "Bihar", "name" => "Jehanabad" ],
            [ "state_name" => "Bihar", "name" => "Kaimur" ],
            [ "state_name" => "Bihar", "name" => "Katihar" ],
            [ "state_name" => "Bihar", "name" => "Khagaria" ],
            [ "state_name" => "Bihar", "name" => "Kishanganj" ],
            [ "state_name" => "Bihar", "name" => "Lakhisarai" ],
            [ "state_name" => "Bihar", "name" => "Madhepura" ],
            [ "state_name" => "Bihar", "name" => "Madhubani" ],
            [ "state_name" => "Bihar", "name" => "Munger" ],
            [ "state_name" => "Bihar", "name" => "Muzaffarpur" ],
            [ "state_name" => "Bihar", "name" => "Nalanda" ],
            [ "state_name" => "Bihar", "name" => "Nawada" ],
            [ "state_name" => "Bihar", "name" => "Paschim Champaran" ],
            [ "state_name" => "Bihar", "name" => "Patna" ],
            [ "state_name" => "Bihar", "name" => "Purnia" ],
            [ "state_name" => "Bihar", "name" => "Purvi Champaran" ],
            [ "state_name" => "Bihar", "name" => "Rohtas" ],
            [ "state_name" => "Bihar", "name" => "Saharsa" ],
            [ "state_name" => "Bihar", "name" => "Samastipur" ],
            [ "state_name" => "Bihar", "name" => "Saran" ],
            [ "state_name" => "Bihar", "name" => "Sheikhpura" ],
            [ "state_name" => "Bihar", "name" => "Sheohar" ],
            [ "state_name" => "Bihar", "name" => "Sitamarhi" ],
            [ "state_name" => "Bihar", "name" => "Siwan" ],
            [ "state_name" => "Bihar", "name" => "Supaul" ],
            [ "state_name" => "Bihar", "name" => "Vaishali" ],
            [ "state_name" => "Chandigarh", "name" =>"Chandigarh" ],
            [ "state_name" => "Chhattisgarh", "name" => "Balod" ],
            [ "state_name" => "Chhattisgarh", "name" => "Balodbazar - Bhatapara" ],
            [ "state_name" => "Chhattisgarh", "name" => "Balramapur" ],
            [ "state_name" => "Chhattisgarh", "name" => "Bastar (Jagdalpur)" ],
            [ "state_name" => "Chhattisgarh", "name" => "Bemetara" ],
            [ "state_name" => "Chhattisgarh", "name" => "Bijapur" ],
            [ "state_name" => "Chhattisgarh", "name" => "Bilaspur" ],
            [ "state_name" => "Chhattisgarh", "name" => "Dakshin Bastar Dantewada" ],
            [ "state_name" => "Chhattisgarh", "name" => "Dhamtari" ],
            [ "state_name" => "Chhattisgarh", "name" => "Durg" ],
            [ "state_name" => "Chhattisgarh", "name" => "Gariyaband" ],
            [ "state_name" => "Chhattisgarh", "name" => "Gorela Pendra Marwahi" ],
            [ "state_name" => "Chhattisgarh", "name" => "Janggir-Champa" ],
            [ "state_name" => "Chhattisgarh", "name" => "Jashpur" ],
            [ "state_name" => "Chhattisgarh", "name" => "Kabirdham" ],
            [ "state_name" => "Chhattisgarh", "name" => "Khairagarh-Chhuikhadan-Gandai" ],
            [ "state_name" => "Chhattisgarh", "name" => "Kondagaon" ],
            [ "state_name" => "Chhattisgarh", "name" => "Korba" ],
            [ "state_name" => "Chhattisgarh", "name" => "Koria" ],
            [ "state_name" => "Chhattisgarh", "name" => "Mahasamund" ],
            [ "state_name" => "Chhattisgarh", "name" => "Manendragarh-Chirmiri-Bharatpur" ],
            [ "state_name" => "Chhattisgarh", "name" => "Mohla-Manpur- Ambagarh Chowki" ],
            [ "state_name" => "Chhattisgarh", "name" => "Mungeli" ],
            [ "state_name" => "Chhattisgarh", "name" => "Narayanpur" ],
            [ "state_name" => "Chhattisgarh", "name" => "Raigarh" ],
            [ "state_name" => "Chhattisgarh", "name" => "Raipur" ],
            [ "state_name" => "Chhattisgarh", "name" => "Rajnandgaon" ],
            [ "state_name" => "Chhattisgarh", "name" => "Sakti" ],
            [ "state_name" => "Chhattisgarh", "name" => "Sarangarh-Bilaigarh" ],
            [ "state_name" => "Chhattisgarh", "name" => "Sarguja" ],
            [ "state_name" => "Chhattisgarh", "name" => "Sukma" ],
            [ "state_name" => "Chhattisgarh", "name" => "Surajpur" ],
            [ "state_name" => "Chhattisgarh", "name" => "Uttar Bastar Kanker" ],
            [ "state_name" => "Dadra Nagar Haveli & Daman-Diu", "name" => "Dadra and Nagar Haveli" ],
            [ "state_name" => "Dadra Nagar Haveli & Daman-Diu", "name" => "Daman" ],
            [ "state_name" => "Dadra Nagar Haveli & Daman-Diu", "name" => "Diu" ],
            [ "state_name" => "Delhi", "name" => "Central Delhi" ],
            [ "state_name" => "Delhi", "name" => "East Delhi" ],
            [ "state_name" => "Delhi", "name" => "New Delhi" ],
            [ "state_name" => "Delhi", "name" => "North Delhi" ],
            [ "state_name" => "Delhi", "name" => "North East Delhi" ],
            [ "state_name" => "Delhi", "name" => "North West Delhi" ],
            [ "state_name" => "Delhi", "name" => "Shahdara" ],
            [ "state_name" => "Delhi", "name" => "South Delhi" ],
            [ "state_name" => "Delhi", "name" => "South East Delhi" ],
            [ "state_name" => "Delhi", "name" => "South West Delhi" ],
            [ "state_name" => "Delhi", "name" => "West Delhi" ],
            [ "state_name" => "Goa", "name" =>"North Goa" ],
            [ "state_name" => "Goa", "name" =>"South Goa" ],
            [ "state_name" => "Gujarat", "name" => "Ahmedabad" ],
            [ "state_name" => "Gujarat", "name" => "Amreli" ],
            [ "state_name" => "Gujarat", "name" => "Anand" ],
            [ "state_name" => "Gujarat", "name" => "Arvalli" ],
            [ "state_name" => "Gujarat", "name" => "Banaskantha" ],
            [ "state_name" => "Gujarat", "name" => "Bharuch" ],
            [ "state_name" => "Gujarat", "name" => "Bhavnagar" ],
            [ "state_name" => "Gujarat", "name" => "Botad" ],
            [ "state_name" => "Gujarat", "name" => "Chhotaudepur" ],
            [ "state_name" => "Gujarat", "name" => "Dahod" ],
            [ "state_name" => "Gujarat", "name" => "Dangs" ],
            [ "state_name" => "Gujarat", "name" => "Devbhumi Dwarka" ],
            [ "state_name" => "Gujarat", "name" => "Gandhinagar" ],
            [ "state_name" => "Gujarat", "name" => "Gir Somnath" ],
            [ "state_name" => "Gujarat", "name" => "Jamnagar" ],
            [ "state_name" => "Gujarat", "name" => "Junagadh" ],
            [ "state_name" => "Gujarat", "name" => "Kachchh" ],
            [ "state_name" => "Gujarat", "name" => "Kheda" ],
            [ "state_name" => "Gujarat", "name" => "Mahesana" ],
            [ "state_name" => "Gujarat", "name" => "Mahisagar" ],
            [ "state_name" => "Gujarat", "name" => "Morbi" ],
            [ "state_name" => "Gujarat", "name" => "Narmada" ],
            [ "state_name" => "Gujarat", "name" => "Navsari" ],
            [ "state_name" => "Gujarat", "name" => "Panchmahal" ],
            [ "state_name" => "Gujarat", "name" => "Patan" ],
            [ "state_name" => "Gujarat", "name" => "Porbandar" ],
            [ "state_name" => "Gujarat", "name" => "Rajkot" ],
            [ "state_name" => "Gujarat", "name" => "Sabarkantha" ],
            [ "state_name" => "Gujarat", "name" => "Surat" ],
            [ "state_name" => "Gujarat", "name" => "Surendranagar" ],
            [ "state_name" => "Gujarat", "name" => "Tapi" ],
            [ "state_name" => "Gujarat", "name" => "Vadodara" ],
            [ "state_name" => "Gujarat", "name" => "Valsad" ],
            [ "state_name" => "Haryana", "name" => "Ambala" ],
            [ "state_name" => "Haryana", "name" => "Bhiwani" ],
            [ "state_name" => "Haryana", "name" => "Charkhi Dadri" ],
            [ "state_name" => "Haryana", "name" => "Faridabad" ],
            [ "state_name" => "Haryana", "name" => "Fatehabad" ],
            [ "state_name" => "Haryana", "name" => "Gurgaon" ],
            [ "state_name" => "Haryana", "name" => "Hissar" ],
            [ "state_name" => "Haryana", "name" => "Jhajjar" ],
            [ "state_name" => "Haryana", "name" => "Jind" ],
            [ "state_name" => "Haryana", "name" => "Kaithal" ],
            [ "state_name" => "Haryana", "name" => "Karnal" ],
            [ "state_name" => "Haryana", "name" => "Kurukshetra" ],
            [ "state_name" => "Haryana", "name" => "Mahendragarh" ],
            [ "state_name" => "Haryana", "name" => "Mewat" ],
            [ "state_name" => "Haryana", "name" => "Palwal" ],
            [ "state_name" => "Haryana", "name" => "Panchkula" ],
            [ "state_name" => "Haryana", "name" => "Panipat" ],
            [ "state_name" => "Haryana", "name" => "Rewari" ],
            [ "state_name" => "Haryana", "name" => "Rohtak" ],
            [ "state_name" => "Haryana", "name" => "Sirsa" ],
            [ "state_name" => "Haryana", "name" => "Sonipat" ],
            [ "state_name" => "Haryana", "name" => "Yamunanagar" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Bilaspur" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Chamba" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Hamirpur" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Kangra" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Kinnaur" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Kullu" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Lahaul \u0026 Spiti" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Mandi" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Shimla" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Sirmour" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Solan" ],
            [ "state_name" => "Himachal Pradesh", "name" => "Una" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Anantnag" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Badgam" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Bandipur" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Baramula" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Doda" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Ganderbal" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Jammu" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Kashmir Displaced" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Kathua" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Kishtwar" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Kulgam" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Kupwara" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Poonch" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Pulwama" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Rajauri" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Ramban" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Reasi" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Samba" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Shopian" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Srinagar" ],
            [ "state_name" => "Jammu and Kashmir", "name" => "Udhampur" ],
            [ "state_name" => "Jharkhand", "name" => "Bokaro" ],
            [ "state_name" => "Jharkhand", "name" => "Chatra" ],
            [ "state_name" => "Jharkhand", "name" => "Deoghar" ],
            [ "state_name" => "Jharkhand", "name" => "Dhanbad" ],
            [ "state_name" => "Jharkhand", "name" => "Dumka" ],
            [ "state_name" => "Jharkhand", "name" => "East Singhbhum" ],
            [ "state_name" => "Jharkhand", "name" => "Garhwa" ],
            [ "state_name" => "Jharkhand", "name" => "Giridih" ],
            [ "state_name" => "Jharkhand", "name" => "Godda" ],
            [ "state_name" => "Jharkhand", "name" => "Gumla" ],
            [ "state_name" => "Jharkhand", "name" => "Hazaribagh" ],
            [ "state_name" => "Jharkhand", "name" => "Jamtara" ],
            [ "state_name" => "Jharkhand", "name" => "Khunti" ],
            [ "state_name" => "Jharkhand", "name" => "Koderma" ],
            [ "state_name" => "Jharkhand", "name" => "Latehar" ],
            [ "state_name" => "Jharkhand", "name" => "Lohardaga" ],
            [ "state_name" => "Jharkhand", "name" => "Pakur" ],
            [ "state_name" => "Jharkhand", "name" => "Palamu" ],
            [ "state_name" => "Jharkhand", "name" => "Ramgarh" ],
            [ "state_name" => "Jharkhand", "name" => "Ranchi" ],
            [ "state_name" => "Jharkhand", "name" => "Sahebganj" ],
            [ "state_name" => "Jharkhand", "name" => "Seraikela Kharsawan" ],
            [ "state_name" => "Jharkhand", "name" => "Simdega" ],
            [ "state_name" => "Jharkhand", "name" => "West Singhbhum" ],
            [ "state_name" => "Karnataka", "name" => "Bagalkot" ],
            [ "state_name" => "Karnataka", "name" => "Bangalore Rural" ],
            [ "state_name" => "Karnataka", "name" => "Bangalore Urban" ],
            [ "state_name" => "Karnataka", "name" => "Belagavi" ],
            [ "state_name" => "Karnataka", "name" => "Bellary" ],
            [ "state_name" => "Karnataka", "name" => "Bidar" ],
            [ "state_name" => "Karnataka", "name" => "Bijapur" ],
            [ "state_name" => "Karnataka", "name" => "Chamarajnagar" ],
            [ "state_name" => "Karnataka", "name" => "Chikkaballapur" ],
            [ "state_name" => "Karnataka", "name" => "Chikmagalur" ],
            [ "state_name" => "Karnataka", "name" => "Chitradurga" ],
            [ "state_name" => "Karnataka", "name" => "Dakshina Kannada" ],
            [ "state_name" => "Karnataka", "name" => "Davangere" ],
            [ "state_name" => "Karnataka", "name" => "Dharwad" ],
            [ "state_name" => "Karnataka", "name" => "Gadag" ],
            [ "state_name" => "Karnataka", "name" => "Gulbarga" ],
            [ "state_name" => "Karnataka", "name" => "Hassan" ],
            [ "state_name" => "Karnataka", "name" => "Haveri" ],
            [ "state_name" => "Karnataka", "name" => "Kodagu" ],
            [ "state_name" => "Karnataka", "name" => "Kolar" ],
            [ "state_name" => "Karnataka", "name" => "Koppal" ],
            [ "state_name" => "Karnataka", "name" => "Mandya" ],
            [ "state_name" => "Karnataka", "name" => "Mysore" ],
            [ "state_name" => "Karnataka", "name" => "Raichur" ],
            [ "state_name" => "Karnataka", "name" => "Ramanagara" ],
            [ "state_name" => "Karnataka", "name" => "Shimoga" ],
            [ "state_name" => "Karnataka", "name" => "Tumkur" ],
            [ "state_name" => "Karnataka", "name" => "Udupi" ],
            [ "state_name" => "Karnataka", "name" => "Uttara Kannada" ],
            [ "state_name" => "Karnataka", "name" => "Vijayanagara" ],
            [ "state_name" => "Karnataka", "name" => "Yadgir" ],
            [ "state_name" => "Kerala", "name" => "Alappuzha" ],
            [ "state_name" => "Kerala", "name" => "Ernakulam" ],
            [ "state_name" => "Kerala", "name" => "Idukki" ],
            [ "state_name" => "Kerala", "name" => "Kannur" ],
            [ "state_name" => "Kerala", "name" => "Kasaragod" ],
            [ "state_name" => "Kerala", "name" => "Kollam" ],
            [ "state_name" => "Kerala", "name" => "Kottayam" ],
            [ "state_name" => "Kerala", "name" => "Kozhikode" ],
            [ "state_name" => "Kerala", "name" => "Malappuram" ],
            [ "state_name" => "Kerala", "name" => "Palakkad" ],
            [ "state_name" => "Kerala", "name" => "Pathanamthitta" ],
            [ "state_name" => "Kerala", "name" => "Thiruvananthapuram" ],
            [ "state_name" => "Kerala", "name" => "Thrissur" ],
            [ "state_name" => "Kerala", "name" => "Wayanad" ],
            [ "state_name" => "Ladakh", "name" => "Kargil" ],
            [ "state_name" => "Ladakh", "name" => "Leh" ],
            [ "state_name" => "Lakshadweep", "name" => "Lakshadweep" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Agar Malwa" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Alirajpur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Anuppur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Ashok Nagar" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Balaghat" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Barwani" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Betul" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Bhind" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Bhopal" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Burhanpur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Chhatarpur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Chhindwara" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Damoh" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Datia" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Dewas" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Dhar" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Dindori" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Guna" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Gwalior" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Harda" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Indore" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Jabalpur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Jhabua" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Katni" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Khandwa(East Nimar)" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Khargone(West Nimar)" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Mandla" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Mandsaur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Mauganj" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Morena" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Narmadapuram" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Narsinghpur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Neemuch" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Niwari" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Panna" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Raisen" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Rajgarh" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Ratlam" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Rewa" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Sagar" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Satna" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Sehore" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Seoni" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Shahdol" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Shajapur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Sheopur" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Shivpuri" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Sidhi" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Singrauli" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Tikamgarh" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Ujjain" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Umaria" ],
            [ "state_name" => "Madhya Pradesh", "name" => "Vidisha" ],
            [ "state_name" => "Maharashtra", "name" => "Ahmednagar" ],
            [ "state_name" => "Maharashtra", "name" => "Akola" ],
            [ "state_name" => "Maharashtra", "name" => "Amravati" ],
            [ "state_name" => "Maharashtra", "name" => "Aurangabad" ],
            [ "state_name" => "Maharashtra", "name" => "Beed" ],
            [ "state_name" => "Maharashtra", "name" => "Bhandara" ],
            [ "state_name" => "Maharashtra", "name" => "Buldhana" ],
            [ "state_name" => "Maharashtra", "name" => "Chandrapur" ],
            [ "state_name" => "Maharashtra", "name" => "Dharashiv" ],
            [ "state_name" => "Maharashtra", "name" => "Dhule" ],
            [ "state_name" => "Maharashtra", "name" => "Gadchiroli" ],
            [ "state_name" => "Maharashtra", "name" => "Gondiya" ],
            [ "state_name" => "Maharashtra", "name" => "Hingoli" ],
            [ "state_name" => "Maharashtra", "name" => "Jalgaon" ],
            [ "state_name" => "Maharashtra", "name" => "Jalna" ],
            [ "state_name" => "Maharashtra", "name" => "Kolhapur" ],
            [ "state_name" => "Maharashtra", "name" => "Latur" ],
            [ "state_name" => "Maharashtra", "name" => "Mumbai City" ],
            [ "state_name" => "Maharashtra", "name" => "Mumbai Suburban" ],
            [ "state_name" => "Maharashtra", "name" => "Nagpur" ],
            [ "state_name" => "Maharashtra", "name" => "Nanded" ],
            [ "state_name" => "Maharashtra", "name" => "Nandurbar" ],
            [ "state_name" => "Maharashtra", "name" => "Nashik" ],
            [ "state_name" => "Maharashtra", "name" => "Palghar" ],
            [ "state_name" => "Maharashtra", "name" => "Parbhani" ],
            [ "state_name" => "Maharashtra", "name" => "Pune" ],
            [ "state_name" => "Maharashtra", "name" => "Raigad" ],
            [ "state_name" => "Maharashtra", "name" => "Ratnagiri" ],
            [ "state_name" => "Maharashtra", "name" => "Sangli" ],
            [ "state_name" => "Maharashtra", "name" => "Satara" ],
            [ "state_name" => "Maharashtra", "name" => "Sindhudurg" ],
            [ "state_name" => "Maharashtra", "name" => "Solapur" ],
            [ "state_name" => "Maharashtra", "name" => "Thane" ],
            [ "state_name" => "Maharashtra", "name" => "Wardha" ],
            [ "state_name" => "Maharashtra", "name" => "Washim" ],
            [ "state_name" => "Maharashtra", "name" => "Yavatmal" ],
            [ "state_name" => "Manipur", "name" => "Bishnupur" ],
            [ "state_name" => "Manipur", "name" => "Chandel" ],
            [ "state_name" => "Manipur", "name" => "Churachandpur" ],
            [ "state_name" => "Manipur", "name" => "Imphal East" ],
            [ "state_name" => "Manipur", "name" => "Imphal West" ],
            [ "state_name" => "Manipur", "name" => "Jiribam" ],
            [ "state_name" => "Manipur", "name" => "Kakching" ],
            [ "state_name" => "Manipur", "name" => "Kamjong" ],
            [ "state_name" => "Manipur", "name" => "Kangpokpi" ],
            [ "state_name" => "Manipur", "name" => "Noney" ],
            [ "state_name" => "Manipur", "name" => "Pherzawl" ],
            [ "state_name" => "Manipur", "name" => "Senapati" ],
            [ "state_name" => "Manipur", "name" => "Tamenglong" ],
            [ "state_name" => "Manipur", "name" => "Tengnoupal" ],
            [ "state_name" => "Manipur", "name" => "Thoubal" ],
            [ "state_name" => "Manipur", "name" => "Ukhrul" ],
            [ "state_name" => "Meghalaya", "name" => "Eastern West Khasi Hills" ],
            [ "state_name" => "Meghalaya", "name" => "East Garo Hills" ],
            [ "state_name" => "Meghalaya", "name" => "East Jaintia Hills" ],
            [ "state_name" => "Meghalaya", "name" => "East Khasi Hills" ],
            [ "state_name" => "Meghalaya", "name" => "North Garo Hills" ],
            [ "state_name" => "Meghalaya", "name" => "RI-BHOI" ],
            [ "state_name" => "Meghalaya", "name" => "South Garo Hills" ],
            [ "state_name" => "Meghalaya", "name" => "South West Garo Hills" ],
            [ "state_name" => "Meghalaya", "name" => "South West Khasi Hills" ],
            [ "state_name" => "Meghalaya", "name" => "West Garo Hills" ],
            [ "state_name" => "Meghalaya", "name" => "West Jaintia Hills" ],
            [ "state_name" => "Meghalaya", "name" => "West Khasi Hills" ],
            [ "state_name" => "Mizoram", "name" => "Aizawl" ],
            [ "state_name" => "Mizoram", "name" => "Champhai" ],
            [ "state_name" => "Mizoram", "name" => "Hnahthial" ],
            [ "state_name" => "Mizoram", "name" => "Khawzawl" ],
            [ "state_name" => "Mizoram", "name" => "Kolasib" ],
            [ "state_name" => "Mizoram", "name" => "Lawngtlai" ],
            [ "state_name" => "Mizoram", "name" => "Lunglei" ],
            [ "state_name" => "Mizoram", "name" => "Mamit" ],
            [ "state_name" => "Mizoram", "name" => "Saitual" ],
            [ "state_name" => "Mizoram", "name" => "Serchhip" ],
            [ "state_name" => "Mizoram", "name" => "Siaha" ],
            [ "state_name" => "Nagaland", "name" => "Chumoukedima" ],
            [ "state_name" => "Nagaland", "name" => "Dimapur" ],
            [ "state_name" => "Nagaland", "name" => "Kiphire" ],
            [ "state_name" => "Nagaland", "name" => "Kohima" ],
            [ "state_name" => "Nagaland", "name" => "Longleng" ],
            [ "state_name" => "Nagaland", "name" => "Mokokchung" ],
            [ "state_name" => "Nagaland", "name" => "Mon" ],
            [ "state_name" => "Nagaland", "name" => "Noklak" ],
            [ "state_name" => "Nagaland", "name" => "Peren" ],
            [ "state_name" => "Nagaland", "name" => "Phek" ],
            [ "state_name" => "Nagaland", "name" => "Pughoboto" ],
            [ "state_name" => "Nagaland", "name" => "Shamator" ],
            [ "state_name" => "Nagaland", "name" => "Tseminyu" ],
            [ "state_name" => "Nagaland", "name" => "Tuensang" ],
            [ "state_name" => "Nagaland", "name" => "Wokha" ],
            [ "state_name" => "Nagaland", "name" => "Zunheboto" ],
            [ "state_name" => "Odisha", "name" => "Angul" ],
            [ "state_name" => "Odisha", "name" => "Balasore" ],
            [ "state_name" => "Odisha", "name" => "Bargarh" ],
            [ "state_name" => "Odisha", "name" => "Bhadrak" ],
            [ "state_name" => "Odisha", "name" => "Bolangir" ],
            [ "state_name" => "Odisha", "name" => "Boudh" ],
            [ "state_name" => "Odisha", "name" => "Cuttack" ],
            [ "state_name" => "Odisha", "name" => "Deogarh" ],
            [ "state_name" => "Odisha", "name" => "Dhenkanal" ],
            [ "state_name" => "Odisha", "name" => "Gajapati" ],
            [ "state_name" => "Odisha", "name" => "Ganjam" ],
            [ "state_name" => "Odisha", "name" => "Jagatsinghpur" ],
            [ "state_name" => "Odisha", "name" => "Jajpur" ],
            [ "state_name" => "Odisha", "name" => "Jharsuguda" ],
            [ "state_name" => "Odisha", "name" => "Kalahandi" ],
            [ "state_name" => "Odisha", "name" => "Kandhamal" ],
            [ "state_name" => "Odisha", "name" => "Kendrapara" ],
            [ "state_name" => "Odisha", "name" => "Keonjhar" ],
            [ "state_name" => "Odisha", "name" => "Khurda" ],
            [ "state_name" => "Odisha", "name" => "Koraput" ],
            [ "state_name" => "Odisha", "name" => "Malkangiri" ],
            [ "state_name" => "Odisha", "name" => "Mayurbhanj" ],
            [ "state_name" => "Odisha", "name" => "Nabarangpur" ],
            [ "state_name" => "Odisha", "name" => "Nayagarh" ],
            [ "state_name" => "Odisha", "name" => "Nuapada" ],
            [ "state_name" => "Odisha", "name" => "Puri" ],
            [ "state_name" => "Odisha", "name" => "Rayagada" ],
            [ "state_name" => "Odisha", "name" => "Sambalpur" ],
            [ "state_name" => "Odisha", "name" => "Subarnapur" ],
            [ "state_name" => "Odisha", "name" => "Sundargarh" ],
            [ "state_name" => "Puducherry", "name" => "Karaikal" ],
            [ "state_name" => "Puducherry", "name" => "Mahe" ],
            [ "state_name" => "Puducherry", "name" => "Puducherry" ],
            [ "state_name" => "Puducherry", "name" => "Yanam" ],
            [ "state_name" => "Punjab", "name" => "Amritsar" ],
            [ "state_name" => "Punjab", "name" => "Barnala" ],
            [ "state_name" => "Punjab", "name" => "Bathinda" ],
            [ "state_name" => "Punjab", "name" => "Faridkot" ],
            [ "state_name" => "Punjab", "name" => "Fatehgarh Sahib" ],
            [ "state_name" => "Punjab", "name" => "Fazilka" ],
            [ "state_name" => "Punjab", "name" => "Firozpur" ],
            [ "state_name" => "Punjab", "name" => "Gurdaspur" ],
            [ "state_name" => "Punjab", "name" => "Hoshiarpur" ],
            [ "state_name" => "Punjab", "name" => "Jalandhar" ],
            [ "state_name" => "Punjab", "name" => "Kapurthala" ],
            [ "state_name" => "Punjab", "name" => "Ludhiana" ],
            [ "state_name" => "Punjab", "name" => "Malerkotla" ],
            [ "state_name" => "Punjab", "name" => "Mansa" ],
            [ "state_name" => "Punjab", "name" => "Moga" ],
            [ "state_name" => "Punjab", "name" => "Pathankot" ],
            [ "state_name" => "Punjab", "name" => "Patiala" ],
            [ "state_name" => "Punjab", "name" => "Rupnagar" ],
            [ "state_name" => "Punjab", "name" => "Sahibzada Ajit Singh Nagar" ],
            [ "state_name" => "Punjab", "name" => "Sangrur" ],
            [ "state_name" => "Punjab", "name" => "Shahid Bhagat Singh Nagar" ],
            [ "state_name" => "Punjab", "name" => "Sri Muktsar Sahib" ],
            [ "state_name" => "Punjab", "name" => "Tarn Taran" ],
            [ "state_name" => "Rajasthan", "name" => "Ajmer" ],
            [ "state_name" => "Rajasthan", "name" => "Alwar" ],
            [ "state_name" => "Rajasthan", "name" => "Banswara" ],
            [ "state_name" => "Rajasthan", "name" => "Baran" ],
            [ "state_name" => "Rajasthan", "name" => "Barmer" ],
            [ "state_name" => "Rajasthan", "name" => "Bharatpur" ],
            [ "state_name" => "Rajasthan", "name" => "Bhilwara" ],
            [ "state_name" => "Rajasthan", "name" => "Bikaner" ],
            [ "state_name" => "Rajasthan", "name" => "Bundi" ],
            [ "state_name" => "Rajasthan", "name" => "Chittorgarh" ],
            [ "state_name" => "Rajasthan", "name" => "Churu" ],
            [ "state_name" => "Rajasthan", "name" => "Dausa" ],
            [ "state_name" => "Rajasthan", "name" => "Dholpur" ],
            [ "state_name" => "Rajasthan", "name" => "Dungarpur" ],
            [ "state_name" => "Rajasthan", "name" => "Ganganagar" ],
            [ "state_name" => "Rajasthan", "name" => "Hanumangarh" ],
            [ "state_name" => "Rajasthan", "name" => "Jaipur" ],
            [ "state_name" => "Rajasthan", "name" => "Jaisalmer" ],
            [ "state_name" => "Rajasthan", "name" => "Jalore" ],
            [ "state_name" => "Rajasthan", "name" => "Jhalawar" ],
            [ "state_name" => "Rajasthan", "name" => "Jhunjhunu" ],
            [ "state_name" => "Rajasthan", "name" => "Jodhpur" ],
            [ "state_name" => "Rajasthan", "name" => "Karauli" ],
            [ "state_name" => "Rajasthan", "name" => "Kota" ],
            [ "state_name" => "Rajasthan", "name" => "Nagaur" ],
            [ "state_name" => "Rajasthan", "name" => "Pali" ],
            [ "state_name" => "Rajasthan", "name" => "Pratapgarh" ],
            [ "state_name" => "Rajasthan", "name" => "Rajsamand" ],
            [ "state_name" => "Rajasthan", "name" => "Sawai Madhopur" ],
            [ "state_name" => "Rajasthan", "name" => "Sikar" ],
            [ "state_name" => "Rajasthan", "name" => "Sirohi" ],
            [ "state_name" => "Rajasthan", "name" => "Tonk" ],
            [ "state_name" => "Rajasthan", "name" => "Udaipur" ],
            [ "state_name" => "Sikkim", "name" => "Gangtok" ],
            [ "state_name" => "Sikkim", "name" => "Geyzing" ],
            [ "state_name" => "Sikkim", "name" => "Mangan" ],
            [ "state_name" => "Sikkim", "name" => "Namchi" ],
            [ "state_name" => "Sikkim", "name" => "Pakyong" ],
            [ "state_name" => "Sikkim", "name" => "Soreng" ],
            [ "state_name" => "Tamil Nadu", "name" => "Ariyalur" ],
            [ "state_name" => "Tamil Nadu", "name" => "Chengalpattu" ],
            [ "state_name" => "Tamil Nadu", "name" => "Chennai" ],
            [ "state_name" => "Tamil Nadu", "name" => "Coimbatore" ],
            [ "state_name" => "Tamil Nadu", "name" => "Cuddalore" ],
            [ "state_name" => "Tamil Nadu", "name" => "Dharmapuri" ],
            [ "state_name" => "Tamil Nadu", "name" => "Dindigul" ],
            [ "state_name" => "Tamil Nadu", "name" => "Erode" ],
            [ "state_name" => "Tamil Nadu", "name" => "Kallakurichi" ],
            [ "state_name" => "Tamil Nadu", "name" => "Kancheepuram" ],
            [ "state_name" => "Tamil Nadu", "name" => "Kanniyakumari" ],
            [ "state_name" => "Tamil Nadu", "name" => "Karur" ],
            [ "state_name" => "Tamil Nadu", "name" => "Krishnagiri" ],
            [ "state_name" => "Tamil Nadu", "name" => "Madurai" ],
            [ "state_name" => "Tamil Nadu", "name" => "Mayiladuthurai" ],
            [ "state_name" => "Tamil Nadu", "name" => "Nagapattinam" ],
            [ "state_name" => "Tamil Nadu", "name" => "Namakkal" ],
            [ "state_name" => "Tamil Nadu", "name" => "Perambalur" ],
            [ "state_name" => "Tamil Nadu", "name" => "Pudukkottai" ],
            [ "state_name" => "Tamil Nadu", "name" => "Ramanathapuram" ],
            [ "state_name" => "Tamil Nadu", "name" => "Ranipet" ],
            [ "state_name" => "Tamil Nadu", "name" => "Salem" ],
            [ "state_name" => "Tamil Nadu", "name" => "Sivaganga" ],
            [ "state_name" => "Tamil Nadu", "name" => "Tenkasi" ],
            [ "state_name" => "Tamil Nadu", "name" => "Thanjavur" ],
            [ "state_name" => "Tamil Nadu", "name" => "Theni" ],
            [ "state_name" => "Tamil Nadu", "name" => "The Nilgiris" ],
            [ "state_name" => "Tamil Nadu", "name" => "Thiruvallur" ],
            [ "state_name" => "Tamil Nadu", "name" => "Thiruvarur" ],
            [ "state_name" => "Tamil Nadu", "name" => "Thoothukudi" ],
            [ "state_name" => "Tamil Nadu", "name" => "Tiruchirappalli" ],
            [ "state_name" => "Tamil Nadu", "name" => "Tirunelveli" ],
            [ "state_name" => "Tamil Nadu", "name" => "Tirupathur" ],
            [ "state_name" => "Tamil Nadu", "name" => "Tiruppur" ],
            [ "state_name" => "Tamil Nadu", "name" => "Tiruvannamalai" ],
            [ "state_name" => "Tamil Nadu", "name" => "Vellore" ],
            [ "state_name" => "Tamil Nadu", "name" => "Viluppuram" ],
            [ "state_name" => "Tamil Nadu", "name" => "Virudhunagar" ],
            [ "state_name" => "Telangana", "name" => "Adilabad" ],
            [ "state_name" => "Telangana", "name" => "Bhadradri Kothagudem" ],
            [ "state_name" => "Telangana", "name" => "Hanumakonda" ],
            [ "state_name" => "Telangana", "name" => "Hyderabad" ],
            [ "state_name" => "Telangana", "name" => "Jagtial" ],
            [ "state_name" => "Telangana", "name" => "Jangaon" ],
            [ "state_name" => "Telangana", "name" => "Jayashankar Bhupalpalle" ],
            [ "state_name" => "Telangana", "name" => "Jogulamba Gadwal" ],
            [ "state_name" => "Telangana", "name" => "Kamareddy" ],
            [ "state_name" => "Telangana", "name" => "Karimnagar" ],
            [ "state_name" => "Telangana", "name" => "Khammam" ],
            [ "state_name" => "Telangana", "name" => "Komaram Bheem Asifabad" ],
            [ "state_name" => "Telangana", "name" => "Mahabubabad" ],
            [ "state_name" => "Telangana", "name" => "Mahbubnagar" ],
            [ "state_name" => "Telangana", "name" => "Mancherial" ],
            [ "state_name" => "Telangana", "name" => "Medak" ],
            [ "state_name" => "Telangana", "name" => "Medchal Malkajgiri" ],
            [ "state_name" => "Telangana", "name" => "Mulugu" ],
            [ "state_name" => "Telangana", "name" => "Nagarkurnool" ],
            [ "state_name" => "Telangana", "name" => "Nalgonda" ],
            [ "state_name" => "Telangana", "name" => "Narayanpet" ],
            [ "state_name" => "Telangana", "name" => "Nirmal" ],
            [ "state_name" => "Telangana", "name" => "Nizamabad" ],
            [ "state_name" => "Telangana", "name" => "Peddapalli" ],
            [ "state_name" => "Telangana", "name" => "Rajanna Sircilla" ],
            [ "state_name" => "Telangana", "name" => "Ranga Reddy" ],
            [ "state_name" => "Telangana", "name" => "Sangareddy" ],
            [ "state_name" => "Telangana", "name" => "Siddipet" ],
            [ "state_name" => "Telangana", "name" => "Suryapet" ],
            [ "state_name" => "Telangana", "name" => "Vikarabad" ],
            [ "state_name" => "Telangana", "name" => "Wanaparthy" ],
            [ "state_name" => "Telangana", "name" => "Warangal" ],
            [ "state_name" => "Telangana", "name" => "Yadadri Bhuvanagiri" ],
            [ "state_name" => "Tripura", "name" => "Dhalai" ],
            [ "state_name" => "Tripura", "name" => "Gomati" ],
            [ "state_name" => "Tripura", "name" => "Khowai" ],
            [ "state_name" => "Tripura", "name" => "North Tripura" ],
            [ "state_name" => "Tripura", "name" => "Sepahijala" ],
            [ "state_name" => "Tripura", "name" => "South Tripura" ],
            [ "state_name" => "Tripura", "name" => "Unakoti" ],
            [ "state_name" => "Tripura", "name" => "West Tripura" ],
            [ "state_name" => "Uttarakhand", "name" => "Almora" ],
            [ "state_name" => "Uttarakhand", "name" => "Bageshwar" ],
            [ "state_name" => "Uttarakhand", "name" => "Chamoli" ],
            [ "state_name" => "Uttarakhand", "name" => "Champawat" ],
            [ "state_name" => "Uttarakhand", "name" => "Dehradun" ],
            [ "state_name" => "Uttarakhand", "name" => "Haridwar" ],
            [ "state_name" => "Uttarakhand", "name" => "Nainital" ],
            [ "state_name" => "Uttarakhand", "name" => "Pauri Garhwal" ],
            [ "state_name" => "Uttarakhand", "name" => "Pithoragarh" ],
            [ "state_name" => "Uttarakhand", "name" => "Rudraprayag" ],
            [ "state_name" => "Uttarakhand", "name" => "Tehri Garhwal" ],
            [ "state_name" => "Uttarakhand", "name" => "Udham Singh Nagar" ],
            [ "state_name" => "Uttarakhand", "name" => "Uttarkashi" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Agra" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Aligarh" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Ambedkar Nagar" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Amethi" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Amroha" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Auraiya" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Ayodhya" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Azamgarh" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Badaun" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Baghpat" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Bahraich" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Ballia" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Balrampur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Banda" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Barabanki" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Bareilly" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Basti" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Bhadohi" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Bijnor" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Bulandshahr" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Chandauli" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Chitrakoot" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Deoria" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Etah" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Etawah" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Farrukhabad" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Fatehpur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Firozabad" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Gautam Buddha Nagar" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Ghaziabad" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Ghazipur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Gonda" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Gorakhpur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Hamirpur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Hapur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Hardoi" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Hathras" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Jalaun" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Jaunpur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Jhansi" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Kannauj" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Kanpur Dehat" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Kanpur Nagar" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Kasganj" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Kaushambi" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Kheri" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Kushinagar" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Lalitpur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Lucknow" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Maharajganj" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Mahoba" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Mainpuri" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Mathura" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Mau" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Meerut" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Mirzapur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Moradabad" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Muzaffarnagar" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Pilibhit" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Pratapgarh" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Prayagraj" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Rae Bareli" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Rampur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Saharanpur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Sambhal" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Sant Kabir Nagar" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Shahjahanpur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Shamli" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Shrawasti" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Siddharthnagar" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Sitapur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Sonbhadra" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Sultanpur" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Unnao" ],
            [ "state_name" => "Uttar Pradesh", "name" => "Varanasi" ],
            [ "state_name" => "West Bengal", "name" => "Alipurduar" ],
            [ "state_name" => "West Bengal", "name" => "Bankura" ],
            [ "state_name" => "West Bengal", "name" => "Birbhum" ],
            [ "state_name" => "West Bengal", "name" => "Coochbehar" ],
            [ "state_name" => "West Bengal", "name" => "Dakshin Dinajpur" ],
            [ "state_name" => "West Bengal", "name" => "Darjeeling" ],
            [ "state_name" => "West Bengal", "name" => "Hooghly" ],
            [ "state_name" => "West Bengal", "name" => "Howrah" ],
            [ "state_name" => "West Bengal", "name" => "Jalpaiguri" ],
            [ "state_name" => "West Bengal", "name" => "Jhargram" ],
            [ "state_name" => "West Bengal", "name" => "Kalimpong" ],
            [ "state_name" => "West Bengal", "name" => "Kolkata" ],
            [ "state_name" => "West Bengal", "name" => "Malda" ],
            [ "state_name" => "West Bengal", "name" => "Murshidabad" ],
            [ "state_name" => "West Bengal", "name" => "Nadia" ],
            [ "state_name" => "West Bengal", "name" => "North 24 Parganas" ],
            [ "state_name" => "West Bengal", "name" => "Paschim Bardhaman" ],
            [ "state_name" => "West Bengal", "name" => "Paschim Medinipur" ],
            [ "state_name" => "West Bengal", "name" => "Purba Bardhaman" ],
            [ "state_name" => "West Bengal", "name" => "Purbo Medinipur" ],
            [ "state_name" => "West Bengal", "name" => "Purulia" ],
            [ "state_name" => "West Bengal", "name" => "South 24 Parganas" ],
            [ "state_name" => "West Bengal", "name" => "Uttar Dinajpur" ]
        ];

        $stateWiseDistricts = [];

        foreach ($districts as $district) {
            $state = $district['state_name'];
            $districtName = $district['name'];

            if (!isset($stateWiseDistricts[$state])) {
                $stateWiseDistricts[$state] = [];
            }

            $stateWiseDistricts[$state][] = $districtName;
        }

        foreach ($stateWiseDistricts as $state => $districts) {
            $state = State::where('name', $state)->first();

            if ($state) {
                foreach ($districts as $district) {
                    $exist = District::where('name', $district)->first();

                    if (!$exist) {
                        $newDistrict = new District();
                        $newDistrict->state_id = $state->id;
                        $newDistrict->name = $district;
                        $newDistrict->save();
                    }
                }
            }
        }
    }
}
